// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/internal/metrics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/internal/metrics.get').default>>>>
    }
    '/api/v1/api-keys/:id/revoke': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/api-keys/[id]/revoke.post').default>>>>
    }
    '/api/v1/api-keys/:id/rotate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/api-keys/[id]/rotate.post').default>>>>
    }
    '/api/v1/api-keys': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/api-keys/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/api-keys/index.post').default>>>>
    }
    '/api/v1/payment-intents/:publicId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/payment-intents/[publicId].get').default>>>>
    }
    '/api/v1/payment-intents': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/payment-intents/index.post').default>>>>
    }
    '/api/v1/providers/scb/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/providers/scb/callback.post').default>>>>
    }
    '/api/webhooks/:provider': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/webhooks/[provider].post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}